name: cdn_netchat_vpn
description: VPN-only module (V2Ray/Xray core) for CDN-NETCHAT.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_v2ray_client: ^1.6.0
  shared_preferences: ^2.2.2
  app_links: ^6.1.4

flutter:
  uses-material-design: true
